name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Tag/Branch version for the image'
        required: true
        default: 'main'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone private repository with specific tag or branch
        run: |
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository_owner }}/myopia.git private-repo
          cd private-repo
          
          # First try to checkout as a tag
          git checkout tags/${{ github.event.inputs.tag_version }} -b build-branch 2>/dev/null || {
            # If tag checkout fails, try as a branch name
            git checkout ${{ github.event.inputs.tag_version }} -b build-branch 2>/dev/null || {
              echo "::error::Neither tag nor branch '${{ github.event.inputs.tag_version }}' found in repository"
              exit 1
            }
          }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./private-repo
          file: ./private-repo/production.Dockerfile
          push: true
          tags: |
            ghcr.io/paulohenriquesg/myopia:${{ github.event.inputs.tag_version }}
            ghcr.io/paulohenriquesg/myopia:latest
          platforms: linux/amd64