name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Tag/Branch version for the image'
        required: true
        default: 'main'

jobs:
  # First job: Clone repository and build base image
  build-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone private repository with specific tag or branch
        run: |
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository_owner }}/myopia.git private-repo
          cd private-repo
          
          # First try to checkout as a tag
          git checkout tags/${{ github.event.inputs.tag_version }} -b build-branch 2>/dev/null || {
            # If tag checkout fails, try as a branch name
            git checkout ${{ github.event.inputs.tag_version }} -b build-branch 2>/dev/null || {
              echo "::error::Neither tag nor branch '${{ github.event.inputs.tag_version }}' found in repository"
              exit 1
            }
          }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./private-repo
          file: ./private-repo/production.base.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/myopia-base:${{ github.event.inputs.tag_version }}
            ghcr.io/${{ github.repository_owner }}/myopia-base:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ github.event.inputs.tag_version }}

  # Second job: Build and push API image (depends on base image)
  build-api-image:
    needs: build-base-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone private repository with specific tag or branch
        run: |
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository_owner }}/myopia.git private-repo
          cd private-repo
          
          # First try to checkout as a tag
          git checkout tags/${{ github.event.inputs.tag_version }} -b build-branch 2>/dev/null || {
            # If tag checkout fails, try as a branch name
            git checkout ${{ github.event.inputs.tag_version }} -b build-branch 2>/dev/null || {
              echo "::error::Neither tag nor branch '${{ github.event.inputs.tag_version }}' found in repository"
              exit 1
            }
          }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./private-repo
          file: ./private-repo/production.api.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/myopia-api:${{ github.event.inputs.tag_version }}
            ghcr.io/${{ github.repository_owner }}/myopia-api:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ github.event.inputs.tag_version }}

  # Third job: Build and push Worker image (depends on base image)
  build-worker-image:
    needs: build-base-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone private repository with specific tag or branch
        run: |
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository_owner }}/myopia.git private-repo
          cd private-repo
          
          # First try to checkout as a tag
          git checkout tags/${{ github.event.inputs.tag_version }} -b build-branch 2>/dev/null || {
            # If tag checkout fails, try as a branch name
            git checkout ${{ github.event.inputs.tag_version }} -b build-branch 2>/dev/null || {
              echo "::error::Neither tag nor branch '${{ github.event.inputs.tag_version }}' found in repository"
              exit 1
            }
          }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Worker Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./private-repo
          file: ./private-repo/production.worker.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/myopia-worker:${{ github.event.inputs.tag_version }}
            ghcr.io/${{ github.repository_owner }}/myopia-worker:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ github.event.inputs.tag_version }}